import { Router } from 'express';
import { authMiddleware } from '../middleware/auth.js';

const router = Router();

const MODELS = [
  {
    id: 'seedance',
    label: 'Seedance 2.0',
    modes: ['text-to-video', 'image-to-video', 'consistency'],
    supportsDuration: true,
    supportsResolution: true,
    supportsAspectRatio: true,
    supportsEndFrame: true,
    supportsConsistencyImages: true,
    maxConsistencyImages: 9,
    resolutionOptions: ['auto', '480p', '720p', '1080p'],
    aspectRatioOptions: ['auto', '16:9', '9:16', '1:1'],
    description: 'Advanced sound-sync technology with atmospheric audio generation.',
    style: 'bg-purple-500/15 text-purple-400 border-purple-500/20',
  },
  {
    id: 'seedance-fast',
    label: 'Seedance 2.0 Fast',
    modes: ['text-to-video', 'image-to-video', 'consistency'],
    supportsDuration: true,
    supportsResolution: true,
    supportsAspectRatio: true,
    supportsEndFrame: true,
    supportsConsistencyImages: true,
    maxConsistencyImages: 9,
    resolutionOptions: ['auto', '480p', '720p', '1080p'],
    aspectRatioOptions: ['auto', '16:9', '9:16', '1:1'],
    description: 'Faster version of Seedance with optimized generation speed.',
    style: 'bg-purple-500/15 text-purple-400 border-purple-500/20',
  },
  {
    id: 'kling-video',
    label: 'Kling 3.0 Cinematic',
    modes: ['text-to-video', 'image-to-video'],
    supportsDuration: true,
    supportsAspectRatio: true,
    supportsEndFrame: true,
    durationOptions: [5, 10],
    aspectRatioOptions: ['16:9', '9:16', '1:1'],
    description: 'State-of-the-art model for dramatic cinematic lighting and deep photorealism.',
    style: 'bg-emerald-500/15 text-emerald-400 border-emerald-500/20',
  },
  {
    id: 'kling-motion',
    label: 'Kling Motion Control',
    modes: ['image-to-video'],
    supportsDuration: false,
    supportsResolution: false,
    supportsAspectRatio: false,
    requiresImage: true,
    requiresMotionVideo: true,
    description: 'Motion transfer: upload a character photo and a reference motion video.',
    style: 'bg-emerald-500/15 text-emerald-400 border-emerald-500/20',
  },
  {
    id: 'sora',
    label: 'OpenAI Sora 2',
    modes: ['text-to-video', 'image-to-video'],
    supportsDuration: true,
    supportsAspectRatio: true,
    durationOptions: [4, 8, 12],
    aspectRatioOptions: ['16:9', '9:16', '1:1'],
    description: "OpenAI's latest video generation model with cinematic quality.",
    style: 'bg-blue-500/15 text-blue-400 border-blue-500/20',
  },
  {
    id: 'veo',
    label: 'Google Veo 3.1 Quality',
    modes: ['text-to-video', 'image-to-video'],
    supportsDuration: true,
    supportsResolution: true,
    supportsAspectRatio: true,
    supportsEndFrame: true,
    resolutionOptions: ['auto', '720p', '1080p', '4k'],
    aspectRatioOptions: ['auto', '16:9', '9:16', '1:1'],
    description: 'Ultra-realistic textures, complex environments, up to 4K capability.',
    style: 'bg-yellow-500/15 text-yellow-400 border-yellow-500/20',
  },
  {
    id: 'veo-fast',
    label: 'Google Veo 3.1 Fast',
    modes: ['text-to-video', 'image-to-video'],
    supportsDuration: true,
    supportsResolution: true,
    supportsAspectRatio: true,
    supportsEndFrame: true,
    resolutionOptions: ['auto', '720p', '1080p'],
    aspectRatioOptions: ['auto', '16:9', '9:16', '1:1'],
    description: 'Faster Veo generation with good quality output.',
    style: 'bg-yellow-500/15 text-yellow-400 border-yellow-500/20',
  },
  {
    id: 'wan-video',
    label: 'Wan 2.2 T2V',
    modes: ['text-to-video'],
    supportsDuration: true,
    supportsResolution: true,
    supportsAspectRatio: true,
    resolutionOptions: ['auto', '480p', '720p'],
    aspectRatioOptions: ['auto', '16:9', '9:16', '1:1'],
    description: 'Text-to-video generation with Wan 2.2 model.',
    style: 'bg-orange-500/15 text-orange-400 border-orange-500/20',
  },
  {
    id: 'wan-image-video',
    label: 'Wan 2.2 I2V',
    modes: ['image-to-video'],
    supportsDuration: true,
    supportsResolution: true,
    supportsEndFrame: true,
    resolutionOptions: ['auto', '480p', '720p'],
    description: 'Image-to-video generation with Wan 2.2 model.',
    style: 'bg-orange-500/15 text-orange-400 border-orange-500/20',
  },
];

// GET /api/models
router.get('/', authMiddleware, (req, res) => {
  res.json(MODELS);
});

export { MODELS };
export default router;
