export const MODELS = [
  {
    id: 'seedance',
    label: 'Seedance 2.0',
    badge: 'Premium',
    modes: ['text-to-video', 'image-to-video', 'consistency'],
    supportsDuration: true,
    supportsResolution: true,
    supportsAspectRatio: true,
    supportsEndFrame: true,
    supportsConsistencyImages: true,
    maxConsistencyImages: 9,
    durationOptions: [5, 10, 15],
    resolutionOptions: ['auto', '480p', '720p', '1080p'],
    aspectRatioOptions: ['auto', '16:9', '9:16', '1:1'],
    description: 'Advanced sound-sync technology with atmospheric audio generation.',
    color: 'purple',
  },
  {
    id: 'seedance-fast',
    label: 'Seedance 2.0 Fast',
    badge: 'Fast',
    modes: ['text-to-video', 'image-to-video', 'consistency'],
    supportsDuration: true,
    supportsResolution: true,
    supportsAspectRatio: true,
    supportsEndFrame: true,
    supportsConsistencyImages: true,
    maxConsistencyImages: 9,
    durationOptions: [5, 10],
    resolutionOptions: ['auto', '480p', '720p', '1080p'],
    aspectRatioOptions: ['auto', '16:9', '9:16', '1:1'],
    description: 'Faster version of Seedance with optimized generation speed.',
    color: 'purple',
  },
  {
    id: 'kling-video',
    label: 'Kling 3.0 Cinematic',
    badge: 'Cinematic',
    modes: ['text-to-video', 'image-to-video'],
    supportsDuration: true,
    supportsAspectRatio: true,
    supportsEndFrame: true,
    durationOptions: [5, 10],
    aspectRatioOptions: ['16:9', '9:16', '1:1'],
    description: 'Dramatic cinematic lighting, deep photorealism, and advanced Start & End frame control.',
    color: 'emerald',
  },
  {
    id: 'kling-motion',
    label: 'Kling Motion Control',
    badge: 'Motion',
    modes: ['image-to-video'],
    supportsDuration: false,
    supportsResolution: false,
    supportsAspectRatio: false,
    requiresImage: true,
    requiresMotionVideo: true,
    description: 'Motion transfer: upload a character photo and a reference motion video.',
    color: 'emerald',
  },
  {
    id: 'sora',
    label: 'OpenAI Sora 2',
    badge: 'Sora',
    modes: ['text-to-video', 'image-to-video'],
    supportsDuration: true,
    supportsAspectRatio: true,
    durationOptions: [4, 8, 12],
    aspectRatioOptions: ['16:9', '9:16', '1:1'],
    description: "OpenAI's latest video generation model with cinematic quality.",
    color: 'blue',
  },
  {
    id: 'veo',
    label: 'Google Veo 3.1 Quality',
    badge: '4K',
    modes: ['text-to-video', 'image-to-video'],
    supportsDuration: true,
    supportsResolution: true,
    supportsAspectRatio: true,
    supportsEndFrame: true,
    durationOptions: [4, 6, 8],
    resolutionOptions: ['auto', '720p', '1080p', '4k'],
    aspectRatioOptions: ['auto', '16:9', '9:16', '1:1'],
    description: 'Ultra-realistic textures, complex environments, up to 4K capability.',
    color: 'yellow',
  },
  {
    id: 'veo-fast',
    label: 'Google Veo 3.1 Fast',
    badge: 'Fast',
    modes: ['text-to-video', 'image-to-video'],
    supportsDuration: true,
    supportsResolution: true,
    supportsAspectRatio: true,
    supportsEndFrame: true,
    durationOptions: [4, 6, 8],
    resolutionOptions: ['auto', '720p', '1080p'],
    aspectRatioOptions: ['auto', '16:9', '9:16', '1:1'],
    description: 'Faster Veo generation with good quality output.',
    color: 'yellow',
  },
  {
    id: 'wan-video',
    label: 'Wan 2.2 T2V',
    badge: 'T2V',
    modes: ['text-to-video'],
    supportsDuration: true,
    supportsResolution: true,
    supportsAspectRatio: true,
    durationOptions: [5, 10],
    resolutionOptions: ['auto', '480p', '720p'],
    aspectRatioOptions: ['auto', '16:9', '9:16', '1:1'],
    description: 'Text-to-video generation with Wan 2.2 model.',
    color: 'orange',
  },
  {
    id: 'wan-image-video',
    label: 'Wan 2.2 I2V',
    badge: 'I2V',
    modes: ['image-to-video'],
    supportsDuration: true,
    supportsResolution: true,
    supportsEndFrame: true,
    durationOptions: [5, 10],
    resolutionOptions: ['auto', '480p', '720p'],
    description: 'Image-to-video generation with Wan 2.2 model.',
    color: 'orange',
  },
];

export function getModel(id) {
  return MODELS.find((m) => m.id === id) || MODELS[0];
}

export const MODE_LABELS = {
  'text-to-video': 'Text to Video',
  'image-to-video': 'Image to Video',
  consistency: 'Consistency',
};
